language: python

python:
  - "3.6"

branches:
  only:
    - master

install:
  - pip install -e .[test]

script:
  - python -m pytest --color=yes -v

after_success:
  - codecov

notifications:
  email: false
